/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ResidentRouteImport } from './routes/resident'
import { Route as ValetRouteImport } from './routes/valet'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEvaluatorsRouteImport } from './routes/admin/evaluators'
import { Route as EvalAgreementRouteImport } from './routes/eval/agreement'
import { Route as EvalPendingRouteImport } from './routes/eval/pending'
import { Route as EvalRevokedRouteImport } from './routes/eval/revoked'
import { Route as EvalTermsRouteImport } from './routes/eval/terms'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const ValetRoute = ValetRouteImport.update({
  id: '/valet',
  path: '/valet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluatorsRoute = AdminEvaluatorsRouteImport.update({
  id: '/admin/evaluators',
  path: '/admin/evaluators',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalAgreementRoute = EvalAgreementRouteImport.update({
  id: '/eval/agreement',
  path: '/eval/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalPendingRoute = EvalPendingRouteImport.update({
  id: '/eval/pending',
  path: '/eval/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRevokedRoute = EvalRevokedRouteImport.update({
  id: '/eval/revoked',
  path: '/eval/revoked',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalTermsRoute = EvalTermsRouteImport.update({
  id: '/eval/terms',
  path: '/eval/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/resident': typeof ResidentRoute
  '/valet': typeof ValetRoute
  '/admin/evaluators': typeof AdminEvaluatorsRoute
  '/eval/agreement': typeof EvalAgreementRoute
  '/eval/pending': typeof EvalPendingRoute
  '/eval/revoked': typeof EvalRevokedRoute
  '/eval/terms': typeof EvalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/resident': typeof ResidentRoute
  '/valet': typeof ValetRoute
  '/admin/evaluators': typeof AdminEvaluatorsRoute
  '/eval/agreement': typeof EvalAgreementRoute
  '/eval/pending': typeof EvalPendingRoute
  '/eval/revoked': typeof EvalRevokedRoute
  '/eval/terms': typeof EvalTermsRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/resident': typeof ResidentRoute
  '/valet': typeof ValetRoute
  '/admin/evaluators': typeof AdminEvaluatorsRoute
  '/eval/agreement': typeof EvalAgreementRoute
  '/eval/pending': typeof EvalPendingRoute
  '/eval/revoked': typeof EvalRevokedRoute
  '/eval/terms': typeof EvalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/login'
    | '/manager'
    | '/resident'
    | '/valet'
    | '/admin/evaluators'
    | '/eval/agreement'
    | '/eval/pending'
    | '/eval/revoked'
    | '/eval/terms'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/login'
    | '/manager'
    | '/resident'
    | '/valet'
    | '/admin/evaluators'
    | '/eval/agreement'
    | '/eval/pending'
    | '/eval/revoked'
    | '/eval/terms'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/login'
    | '/manager'
    | '/resident'
    | '/valet'
    | '/admin/evaluators'
    | '/eval/agreement'
    | '/eval/pending'
    | '/eval/revoked'
    | '/eval/terms'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  ResidentRoute: typeof ResidentRoute
  ValetRoute: typeof ValetRoute
  AdminEvaluatorsRoute: typeof AdminEvaluatorsRoute
  EvalAgreementRoute: typeof EvalAgreementRoute
  EvalPendingRoute: typeof EvalPendingRoute
  EvalRevokedRoute: typeof EvalRevokedRoute
  EvalTermsRoute: typeof EvalTermsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valet': {
      id: '/valet'
      path: '/valet'
      fullPath: '/valet'
      preLoaderRoute: typeof ValetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluators': {
      id: '/admin/evaluators'
      path: '/admin/evaluators'
      fullPath: '/admin/evaluators'
      preLoaderRoute: typeof AdminEvaluatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval/agreement': {
      id: '/eval/agreement'
      path: '/eval/agreement'
      fullPath: '/eval/agreement'
      preLoaderRoute: typeof EvalAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval/pending': {
      id: '/eval/pending'
      path: '/eval/pending'
      fullPath: '/eval/pending'
      preLoaderRoute: typeof EvalPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval/revoked': {
      id: '/eval/revoked'
      path: '/eval/revoked'
      fullPath: '/eval/revoked'
      preLoaderRoute: typeof EvalRevokedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval/terms': {
      id: '/eval/terms'
      path: '/eval/terms'
      fullPath: '/eval/terms'
      preLoaderRoute: typeof EvalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  ResidentRoute: ResidentRoute,
  ValetRoute: ValetRoute,
  AdminEvaluatorsRoute: AdminEvaluatorsRoute,
  EvalAgreementRoute: EvalAgreementRoute,
  EvalPendingRoute: EvalPendingRoute,
  EvalRevokedRoute: EvalRevokedRoute,
  EvalTermsRoute: EvalTermsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
